### ISSUE TITLE
deeptrafo() throws error when response is structured as Surv() object

### ISSUE THREAD

**Issue by danleibovitz** [neural-structured-additive-learning/deeptrafo#45]
Hello!

When calling `deeptrafo()` to initiate a model on a simple survival dataset, e.g., `pbc` from the `survival` package, I receive:

> `Error in y[, 1] : incorrect number of dimensions`

From appendix B of the article _Estimating Conditional Distributions with Neural: Networks using R Package deeptrafo_, we have that "Censored responses can be supplied as ‘Surv’ objects", however, I have so far been unable to specify any model with a `Surv` object as a response. 

I've also looked through the test cases and observed that tests of survival models are not run with `Surv` objects. Is there an alternate syntax that should be used for specifying censored survival models with `deeptrafo`?

Reproducible example:
```R
library(dplyr)

pbc <- survival::pbc

# Convert to 0/1 standard where 1 indicates event
pbc <- pbc %>% mutate(
  day = 0,
  status = case_when(
    status == 0 ~ 0,
    status == 1 ~ 0,
    status == 2 ~ 1
  )
)

mod1 <- deeptrafo(formula = Surv(time, status) | protime ~ bili, 
                  data = pbc, 
                  response_type = "survival"
)

```

**Comment by LucasKook** [comment]
Hi Daniel -- I can reproduce the error. The problem is that `deeptrafo` does not evaluate the LHS of the formula and you need to create the Survival object beforehand like this:

```r
library("deeptrafo")
library("survival")
library("dplyr")

pbc <- survival::pbc

# Convert to 0/1 standard where 1 indicates event
pbc <- pbc %>% mutate(
  day = 0,
  status = case_when(
    status == 0 ~ 0,
    status == 1 ~ 0,
    status == 2 ~ 1
  ),
  surv = Surv(time, status)
)

mod1 <- deeptrafo(formula = surv | protime ~ bili, 
                  data = pbc, 
                  response_type = "survival"
)
```
Please let me know if this solves your issue.

**Comment by danleibovitz** [comment]
Thanks @LucasKook, this solves _this_ issue, and opens another just as fast. I'll open a new issue as I'm not absolutely sure they're related.
